const TAG = "wallet-service";

const DEFAULT_BALANCE_REFRESH_TIMEOUT_MS = 30000;
const MAX_WALLETS_PER_BATCH = 50;
const BALANCE_FETCH_RETRY_ATTEMPTS = 3;
const BALANCE_FETCH_RETRY_DELAY_MS = 1000;

const MAX_WALLETS_PER_CREATE_REQUEST = 100;
const DEFAULT_WALLET_LABEL_PREFIX = "Wallet";

const SOLANA_PUBLIC_KEY_LENGTH = 44;
const SOLANA_SECRET_KEY_LENGTH = 88; // Base58 encoded

export {
  BALANCE_FETCH_RETRY_ATTEMPTS,
  BALANCE_FETCH_RETRY_DELAY_MS,
  DEFAULT_BALANCE_REFRESH_TIMEOUT_MS,
  DEFAULT_WALLET_LABEL_PREFIX,
  MAX_WALLETS_PER_BATCH,
  MAX_WALLETS_PER_CREATE_REQUEST,
  SOLANA_PUBLIC_KEY_LENGTH,
  SOLANA_SECRET_KEY_LENGTH,
  TAG,
};
